version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080

  client:
    build: ./client
    ports:
      - 3000:3000

  db:
    build: ./db/mysql
    ports:
      - 3306:
